name: stats-readme

on:
    schedule:
        - cron: 0 0 * * *
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v6

            - name: Get current timestamp
              id: timestamp
              run: echo "time=$(date -u +'%Y-%m-%d %H:%M UTC')" >> $GITHUB_OUTPUT

            - name: Generate stats card
              uses: readme-tools/github-readme-stats-action@v1
              with:
                  card: stats
                  options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&hide_title=true&hide_border=true&
                  path: profile/stats.svg
                  token: ${{ secrets.GH_STATS_TOKEN }}

            - name: Generate streak stats card
              uses: kurtismassey/github-readme-streak-stats@fix/run-in-action-dir
              with:
                  USERNAME: ${{ github.repository_owner }}
                  GITHUB_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
                  THEME: tokyonight
                  OUTPUT_PATH: profile/streaks.svg
                  HIDE_BORDER: true

            - name: Commit and push cards
              run: |
                  git config user.name "Kurtis Massey"
                  git config user.email ${{ vars.GIT_EMAIL }}
                  git add profile/*.svg
                  git diff --staged --quiet || git commit -m "docs(README): update stats and streaks cards (${{ steps.timestamp.outputs.time }})"
                  git pull --rebase origin main
                  git push
